services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe cluster"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - cassandra-network

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    depends_on:
      - cassandra-node1
    networks:
      - cassandra-network

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
    depends_on:
      - cassandra-node2
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
